name: Trabalho vendo arquivos compartilhados entre steps

on:
  push: 
    branches:
      - main

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versao do ubuntu
        run: cat /etc/os-release

      - name: Exibir uma mensagem
        run: echo "Estou fazendo um curso de GitHub Actions da Linuztips" > ${{ github.workspace }}/mensagem.txt

      - uses: actions/upload-artifact@v7
        with:
          name: strigus
          path: ${{ github.workspace }}/mensagem.txt
      
  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: Ver o conteudo do diretorio
        run: ls -lha 

      - uses: actions/download-artifact@v8
        with:
          name: strigus
          path: mensagem.txt

      - name: Ver o conteudo do diretorio
        run: ls -lha && ls ./strigus/

      - name: Acessa arquivo mensagem
        run: mv strigus/mensagem.txt . && rm -rf ./strigus

      - name: Ver o conteudo do diretorio
        run: ls -lha 

      - name: Acessa arquivo mensage,
        run: cat mensagem.txt
      