name: Primeiro Workflow Linuxtips

on:
  push: 
    branches:
      - main

jobs:
  entre-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versao do ubuntu
        run: cat /etc/os-release

      - name: Exibir uma mensagem
        run: echo "Estou fazendo um curso de GitHub Actions da Linuztips" > mensagem.txt
      
      - name: Qualquer outra coisa
        run: ls -lha

      - name: Le conteudo do arquivo
        run: cat mensagem.txt

      